### ISSUE TITLE
[Linux] Failure to inject.

### ISSUE THREAD

**Issue by Antiswitcher** [kmaork/pyinjector#1]
```
lafont@lafont-G3-3579:~/Desktop/csgo/injector/linux-inject-master$ inject 26609 /home/lafont/Desktop/csgo/injector/linux_so_injector-master/libGOESP.so
Traceback (most recent call last):
  File "/home/lafont/.local/bin/inject", line 8, in <module>
    sys.exit(main())
  File "/home/lafont/.local/lib/python3.6/site-packages/pyinjector/__main__.py", line 15, in main
    inject(parsed_args.pid, parsed_args.library_path)
  File "/home/lafont/.local/lib/python3.6/site-packages/pyinjector/pyinjector.py", line 47, in inject
    injector = Injector.attach(pid)
  File "/home/lafont/.local/lib/python3.6/site-packages/pyinjector/pyinjector.py", line 33, in attach
    call_c_func(libinjector.injector_attach, byref(injector_p), pid)
  File "/home/lafont/.local/lib/python3.6/site-packages/pyinjector/pyinjector.py", line 22, in call_c_func
    assert ret == 0, '{} returned {}, see injector/include/injector.h'.format(func.__name__, ret)
AssertionError: injector_attach returned -8, see injector/include/injector.h
```

**Comment by kmaork** [comment]
Hey @Antiswitcher , this is a permission error.
Since some kernel version, the scope of processes which ptrace can attach to was limited for security purposes. Sometimes, for pyinjector to work, you might need to run it as root, or remove these limitations as detailed in [this answer](https://stackoverflow.com/a/32274645/2907819).
