### ISSUE TITLE
undefined symbol: injector_attach

### ISSUE THREAD

**Issue by alex-eri** [kmaork/pyinjector#11]
System is  Debian GNU/Linux 10 (buster) running Python 3.7.3

Installed debugger as 
```
apt install  --no-install-recommends python3-pip python3-setuptools python3-wheel python3-dev build-essential
python3 -m pip install madbg
```

I have this trace trying to attach:

```
# python3 -m madbg attach 18964
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.7/dist-packages/madbg/__init__.py", line 1, in <module>
    from .api import set_trace, set_trace_on_connect, post_mortem, run_with_debugging, attach_to_process
  File "/usr/local/lib/python3.7/dist-packages/madbg/api.py", line 10, in <module>
    from hypno import inject_py
  File "/usr/local/lib/python3.7/dist-packages/hypno/__init__.py", line 1, in <module>
    from .hypno import inject_py
  File "/usr/local/lib/python3.7/dist-packages/hypno/hypno.py", line 4, in <module>
    from pyinjector import inject
  File "/usr/local/lib/python3.7/dist-packages/pyinjector/__init__.py", line 1, in <module>
    from .pyinjector import inject, LibraryNotFoundException
  File "/usr/local/lib/python3.7/dist-packages/pyinjector/pyinjector.py", line 13, in <module>
    libinjector.injector_attach.argtypes = POINTER(injector_pointer_t), pid_t
  File "/usr/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/python3.7/dist-packages/pyinjector/libinjector.cpython-37m-x86_64-linux-gnu.so: undefined symbol: injector_attach
```

**Comment by kmaork** [comment]
Thank you, fixed in `pyinjector==1.0.5`
